// src/components/CitySearch.jsx

import { useState, useEffect, useRef } from "react";
import { Search, MapPin, X, Loader2 } from "lucide-react";
import { geocodeCity } from "../services/weatherApi";

export default function CitySearch({ onSelect }) {
  const [query, setQuery] = useState("");
    const [results, setResults] = useState([]);
      const [loading, setLoading] = useState(false);
        const [open, setOpen] = useState(false);
          const [error, setError] = useState(null);
            const containerRef = useRef(null);
              const inputRef = useRef(null);

                // Debounced search — waits 300ms after user stops typing
                  useEffect(() => {
                      if (query.trim().length < 2) {
                            setResults([]);
                                  setError(null);
                                        return;
                                            }

                                                setLoading(true);
                                                    const timer = setTimeout(async () => {
                                                          try {
                                                                  const cities = await geocodeCity(query.trim());
                                                                          setResults(cities);
                                                                                  setError(null);
                                                                                        } catch (err) {
                                                                                                setError("Search failed");
                                                                                                        setResults([]);
                                                                                                              } finally {
                                                                                                                      setLoading(false);
                                                                                                                            }
                                                                                                                                }, 300);

                                                                                                                                    return () => clearTimeout(timer);
                                                                                                                                      }, [query]);

                                                                                                                                        // Close dropdown when clicking outside
                                                                                                                                          useEffect(() => {
                                                                                                                                              function handleClickOutside(e) {
                                                                                                                                                    if (containerRef.current && !containerRef.current.contains(e.target)) {
                                                                                                                                                            setOpen(false);
                                                                                                                                                                  }
                                                                                                                                                                      }
                                                                                                                                                                          document.addEventListener("mousedown", handleClickOutside);
                                                                                                                                                                              return () => document.removeEventListener("mousedown", handleClickOutside);
                                                                                                                                                                                }, []);

                                                                                                                                                                                  // Handle result selection
                                                                                                                                                                                    const handleSelect = (city) => {
                                                                                                                                                                                        onSelect({
                                                                                                                                                                                              lat: city.latitude,
                                                                                                                                                                                                    lon: city.longitude,
                                                                                                                                                                                                          name: city.name,
                                                                                                                                                                                                                country: city.country || "",
                                                                                                                                                                                                                    });
                                                                                                                                                                                                                        setQuery("");
                                                                                                                                                                                                                            setResults([]);
                                                                                                                                                                                                                                setOpen(false);
                                                                                                                                                                                                                                    inputRef.current?.blur();
                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                        // Keyboard: Enter selects first result, Escape closes
                                                                                                                                                                                                                                          const handleKeyDown = (e) => {
                                                                                                                                                                                                                                              if (e.key === "Escape") {
                                                                                                                                                                                                                                                    setOpen(false);
                                                                                                                                                                                                                                                          inputRef.current?.blur();
                                                                                                                                                                                                                                                              } else if (e.key === "Enter" && results.length > 0) {
                                                                                                                                                                                                                                                                    e.preventDefault();
                                                                                                                                                                                                                                                                          handleSelect(results[0]);
                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                  const handleClear = () => {
                                                                                                                                                                                                                                                                                      setQuery("");
                                                                                                                                                                                                                                                                                          setResults([]);
                                                                                                                                                                                                                                                                                              inputRef.current?.focus();
                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                  const showDropdown = open && (loading || results.length > 0 || error);

                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                        <div className="city-search" ref={containerRef}>
                                                                                                                                                                                                                                                                                                              <div className="city-search-input-wrap">
                                                                                                                                                                                                                                                                                                                      <Search size={14} className="city-search-icon" />
                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                        ref={inputRef}
                                                                                                                                                                                                                                                                                                                                                  type="text"
                                                                                                                                                                                                                                                                                                                                                            value={query}
                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => {
                                                                                                                                                                                                                                                                                                                                                                                  setQuery(e.target.value);
                                                                                                                                                                                                                                                                                                                                                                                              setOpen(true);
                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                  onFocus={() => setOpen(true)}
                                                                                                                                                                                                                                                                                                                                                                                                                            onKeyDown={handleKeyDown}
                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="Search city…"
                                                                                                                                                                                                                                                                                                                                                                                                                                                className="city-search-input"
                                                                                                                                                                                                                                                                                                                                                                                                                                                          aria-label="Search for a city"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    aria-expanded={showDropdown}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              aria-controls="city-search-results"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        autoComplete="off"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {query && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={handleClear}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="city-search-clear"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  aria-label="Clear search"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <X size={14} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {showDropdown && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div id="city-search-results" className="city-search-dropdown" role="listbox">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {loading && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="city-search-state">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Loader2 size={14} className="city-search-spinner" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span>Searching…</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {!loading && error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="city-search-state city-search-state--error">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {error}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {!loading && !error && results.length === 0 && query.length >= 2 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="city-search-state">No cities found</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {!loading && results.map((city) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={`${city.latitude}-${city.longitude}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => handleSelect(city)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="city-search-result"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              role="option"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <MapPin size={14} className="city-search-result-icon" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="city-search-result-text">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="city-search-result-name">{city.name}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="city-search-result-meta">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {city.admin1 && <span>{city.admin1}</span>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {city.admin1 && city.country && <span> · </span>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {city.country && <span>{city.country}</span>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }